[package]
name = "go22dos"
version = "0.1.0"
edition = "2021"

[dependencies]
ncurses = "5.101.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.8"
thiserror = "1.0"
whoami = "1.5.2"
